cc_binary(
    name = "Motara.MediaPipe.Native.dll",
    srcs = ["MediaPipeBridge.cc", "MediaPipeBridge.h"],
    linkshared = True,
    deps = ["//mediapipe/tasks/c/vision/face_landmarker:face_landmarker_lib"],
    visibility = ["//visibility:public"],
)
